ollama pull codegemma:7b
ollama pull codestral
ollama pull deepseek-coder:6.7b
ollama pull deepseek-r1:14b
ollama pull deepseek-r1:8b
ollama pull devstral-small-2:24b
ollama pull gemma2:9b
ollama pull gemma4:26b
ollama pull gpt-oss:120b
ollama pull gpt-oss:20b
ollama pull llama3.1:8b
ollama pull mistral:7b
ollama pull qwen2.5-coder:14b
ollama pull qwen2.5-coder:7b
ollama pull qwen3.5:9b
ollama pull qwen3.5:4b
ollama pull qwen3.5:2b
ollama pull qwen3:8b
ollama pull qwen3:14b
ollama pull qwen3:4b
